# Herencia

In [9]:
class Animal: #Clase base, padre o super clase
    def __init__(self, nombre,edad,raza):
        self.nombre = nombre
        self.edad = edad
        self.raza = raza

    def __str__(self):
        return f"{self.nombre} con una edad: {self.edad} años y de raza:{self.raza}"
    
    def correr(self):
        return f"{self.nombre} esta corriendo"

In [10]:
class Perro(Animal): #Clase hija o sub clase
    def __init__(self, nombre, edad, raza, color):
        super().__init__(nombre, edad, raza) #Llamamos al constructor de la clase padre
        self.color = color

    def __str__(self):
        return f"{super().__str__()} y de color: {self.color}"
    
    def ladrar(self):
        return f"{self.nombre} esta ladrando"

In [11]:
class Gato(Animal): #Clase hija o sub clase
    def __init__(self, nombre, edad, raza, tamanio):
        super().__init__(nombre, edad, raza) #Llamamos al constructor de la clase padre
        self.tamanio = tamanio

    def __str__(self):
        return f"{super().__str__()} y de tamaño: {self.tamanio}"
    
    def maullar(self):
        return f"{self.nombre} esta maullando"

In [12]:
gato1 = Gato("Michi", 2, "Siames", "Pequeño")
perro1 = Perro("Firulais", 3, "Labrador", "Negro")

print(gato1)
print(perro1)
print(gato1.maullar())
print(perro1.ladrar())
print(gato1.correr())
print(perro1.correr())

Michi con una edad: 2 años y de raza:Siames y de tamaño: Pequeño
Firulais con una edad: 3 años y de raza:Labrador y de color: Negro
Michi esta maullando
Firulais esta ladrando
Michi esta corriendo
Firulais esta corriendo

# Agregaciòn

In [13]:
class Bala:
    def __init__(self,id,marca):
        self.id = id
        self.marca = marca
    
    def __str__(self):
        return f"Bala con id: {self.id} y marca: {self.marca}"

In [14]:
class Jugador:
    def __init__(self,nombre):
        self.nombre = nombre    

    def __str__(self):
        return f"Jugador con nombre: {self.nombre}"   
    
    def disparar(self,objeto_bala):
        return f"{self.nombre} esta disparando a {objeto_bala}"

In [ ]:
objeto_bala = Bala(1,"Glock")
jugador1 = Jugador("Cosner")

print(objeto_bala)
print(jugador1)
print(jugador1.disparar(objeto_bala))

Bala con id: 1 y marca: Glock
Jugador con nombre: Cosner
Cosner esta disparando a Bala con id: 1 y marca: Glock

# Composiciòn

In [16]:
class Motor:
    def __init__(self, marca, modelo):
        self.marca = marca
        self.modelo = modelo
    
    def __str__(self):
        return f"Motor de marca: {self.marca} y modelo: {self.modelo}"

    def arrancar(self):
        return f"El motor {self.marca} {self.modelo} esta arrancando"

In [ ]:
class Carro:
    def __init__(self, marca_carro, color,marca_motor, modelo):
        self.marca = marca_carro
        self.color = color
        self.objeto_motor = Motor(marca_motor, modelo)
    
    def __str__(self):
        return f"Carro de marca: {self.marca}, color: {self.color} y con motor: {self.objeto_motor}"

    def conducir(self):
        return f"El carro {self.marca} {self.color} esta siendo conducido"

In [20]:
objeto_carro = Carro("Toyota", "Rojo", "Honda", "Civic")
print(objeto_carro)
print(objeto_carro.conducir())

del objeto_carro

Carro de marca: Toyota, color: Rojo y con motor: Motor de marca: Honda y modelo: Civic
El carro Toyota Rojo esta siendo conducido

# Ejercicio 1

In [25]:
class Computadora:
    __lista = [] #Atributo de clase o atributo estatico

    def __init__(self,precio, procesador, pantalla):
        self.precio = precio
        self.procesador = procesador
        self.pantalla = pantalla
        self.precio_final = self.precio
    
    def __str__(self):
        return f"Computadora con precio: {self.precio}, procesador: {self.procesador} y pantalla: {self.pantalla} y precio final: {self.precio_final}"
    
    def agregar_computadora(self, objeto_computadora):
        self.__lista.append(objeto_computadora)
    
    def mostrar_computadoras(self):
        for computadora in self.__lista:
            print(computadora)

    def calcular_precio_total(self):
        pass
    
    @property
    def precio(self):
        return self.__precio
    @precio.setter
    def precio(self, precio):
        self.__precio = precio
    
    @property
    def procesador(self):
        return self.__procesador
    @procesador.setter
    def procesador(self, procesador):
        self.__procesador = procesador

    @property
    def pantalla(self):
        return self.__pantalla  
    @pantalla.setter
    def pantalla(self, pantalla):
        self.__pantalla = pantalla

In [ ]:
class Laptop(Computadora):
    def __init__(self, precio, procesador, pantalla):
        super().__init__(precio, procesador, pantalla)
        self.calcular_precio_total()
        
    def calcular_precio_total(self):
        # procesador
        if self.procesador == "i5":
            self.precio_final += self.precio * 0.1
        elif self.procesador == "i7":
            self.precio_final += self.precio * 0.15

        # pantalla
        if self.pantalla == "táctil":
            self.precio_final += self.precio * 0.05

In [ ]:
class Desketop(Computadora):
    def __init__(self, precio, procesador, pantalla):
        super().__init__(precio, procesador, pantalla)
        self.calcular_precio_total()
        
    def calcular_precio_total(self):
        # procesador
        if self.procesador == "i5":
            self.precio_final += self.precio * 0.08
        elif self.procesador == "i7":
            self.precio_final += self.precio * 0.12

        # pantalla
        if self.pantalla == "HD":
            self.precio_final += 200
        elif self.pantalla == "4K":
            self.precio_final += 300

In [28]:
objeto1_laptop = Laptop(1000, "i7", "táctil")
objeto2_laptop = Laptop(1000, "i5", "normal")


objeto1_desktop = Desketop(600, "i5", "4K")
objeto2_desktop = Desketop(600, "i7", "HD")

objeto1_laptop.agregar_computadora(objeto1_laptop)
objeto1_laptop.agregar_computadora(objeto2_laptop)
objeto1_desktop.agregar_computadora(objeto1_desktop)
objeto1_desktop.agregar_computadora(objeto2_desktop)

objeto1_laptop.mostrar_computadoras()

Computadora con precio: 1000, procesador: i7 y pantalla: táctil y precio final: 1200.0
Computadora con precio: 1000, procesador: i5 y pantalla: normal y precio final: 1100.0
Computadora con precio: 600, procesador: i5 y pantalla: 4K y precio final: 948.0
Computadora con precio: 600, procesador: i7 y pantalla: HD y precio final: 872.0

# Ejercicio 2

In [39]:
class Volumen:
    def __init__(self,id,name):
        self.id = id
        self.name = name
    
    def __str__(self):
        return f"Volumen con id: {self.id} y nombre: {self.name}"

    @property
    def id(self):
        return self.__id
    @id.setter
    def id(self, id):
        self.__id = id

    @property
    def name(self):
        return self.__name
    @name.setter
    def name(self, name):
        self.__name = name

In [40]:
class Book(Volumen):
    def __init__(self, id, name, code):
        super().__init__(id, name)
        self.code = code
    
    def __str__(self):
        return f"{super().__str__()} y isbn: {self.code}"

    @property
    def code(self):
        return self.__code
    @code.setter
    def code(self, code):
        self.__code = code

In [41]:
class Newpaper(Volumen):
    def __init__(self, id, name, code):
        super().__init__(id, name)
        self.code = code
    
    def __str__(self):
        return f"{super().__str__()} y issn: {self.code}"

    @property
    def code(self):
        return self.__code
    @code.setter
    def code(self, code):
        self.__code = code

In [ ]:
import pandas as pd

class Library:
    def __init__(self,name,address):
        self.name = name
        self.address = address
        self.__list_volumenes = []
    
    def __str__(self):
        return f"Library con nombre: {self.name} y direccion: {self.address}"
    
    def add_volumen(self, objeto_volumen):
        self.__list_volumenes.append(objeto_volumen)
    
    def remove_volumen(self, id):
        for volumen in self.__list_volumenes:
            if volumen.id == id:
                self.__list_volumenes.remove(volumen)
                print(f"Volumen con id: {id} eliminado")
                break
        print(f"Volumen con id: {id} no encontrado")
    
    def show_volumens(self):
        for volumen in self.__list_volumenes:
            print(volumen)
    
    def save_volumens(self):
        lista_id = []
        lista_name = []
        lista_code = []

        for volumen in self.__list_volumenes:
            lista_id.append(volumen.id)
            lista_name.append(volumen.name)
            lista_code.append(volumen.code)


        df = pd.DataFrame({
            "id": lista_id,
            "name": lista_name,
            "code": lista_code
        })

        df.to_excel("volumnens.xlsx",index=False)
        print("Volumenes guardados en el archivo volumen.xlsx")

In [45]:
objeto_library = Library("Biblioteca Central", "Av. Principal 123")
objeto_book = Book(1, "El Quijote", "1234567890")
objeto_newspaper = Newpaper(2, "El Comercio", "0987654321")

objeto_library.add_volumen(objeto_book)
objeto_library.add_volumen(objeto_newspaper)
objeto_library.show_volumens()
objeto_library.save_volumens()

Volumen con id: 1 y nombre: El Quijote y isbn: 1234567890
Volumen con id: 2 y nombre: El Comercio y issn: 0987654321
Volumenes guardados en el archivo volumen.xlsx

In [ ]:
#Leer el archivo guardado
df = pd.read_excel("volumnens.xlsx")
df

   id         name        code
0   1   El Quijote  1234567890
1   2  El Comercio   987654321

# Ejemplo de Pandas

In [29]:
import pandas as pd

In [32]:
data = {
    "codigos":["u2024001","u2024002","u2024003"],
    "nombres":["Juan","Ana","Pedro"],
    "notas":[18, 15, 20]
}

df = pd.DataFrame(data)
df

    codigos nombres  notas
0  u2024001    Juan     18
1  u2024002     Ana     15
2  u2024003   Pedro     20

In [38]:
df["notas"]

0    18
1    15
2    20
Name: notas, dtype: int64